# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/zoticus/project_2/project_2.srcs/sources_1/ip/arctan_0/arctan_0.xci
# IP: The module: 'arctan_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zoticus/project_2/project_2.srcs/sources_1/ip/arctan_0/arctan_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arctan_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/zoticus/project_2/project_2.srcs/sources_1/ip/arctan_0/arctan_0.xci
# IP: The module: 'arctan_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zoticus/project_2/project_2.srcs/sources_1/ip/arctan_0/arctan_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arctan_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
