# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/zoticus/DSP_RDv6/DSP_RDv6.srcs/sources_1/ip/xadc_dsp_1/xadc_dsp.xci
# IP: The module: 'xadc_dsp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zoticus/DSP_RDv6/DSP_RDv6.srcs/sources_1/ip/xadc_dsp_1/xadc_dsp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_dsp'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zoticus/DSP_RDv6/DSP_RDv6.srcs/sources_1/ip/xadc_dsp_1/xadc_dsp.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_dsp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/zoticus/DSP_RDv6/DSP_RDv6.srcs/sources_1/ip/xadc_dsp_1/xadc_dsp.xci
# IP: The module: 'xadc_dsp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zoticus/DSP_RDv6/DSP_RDv6.srcs/sources_1/ip/xadc_dsp_1/xadc_dsp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_dsp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zoticus/DSP_RDv6/DSP_RDv6.srcs/sources_1/ip/xadc_dsp_1/xadc_dsp.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_dsp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
